#!/usr/bin/env python3
"""check_stepF2.py -- F2: is the documentation true, not just present?

F2's verify clause is "following the README from a clean clone reproduces E4's output". Nobody can
clone-and-run inside a gate, but almost everything that makes that claim *true* is checkable, and the
ways a README goes false are exactly the ways it drifts:

* every command it prints must exist -- each `python -m tools.puzzle <stage>` must be a stage in
  `cli.STAGES`, and each `tools/checks/<file>.py` must be a gate on disk;
* its counts must be current: the gate count it states must equal the number of gates the suite
  actually discovers, so adding a gate without touching the README fails here;
* the prerequisites it lists must be the real ones -- the upstream puzzle repo, `requirements.txt`,
  `iverilog`, `git` -- because those are what the pipeline refuses to run without;
* the output it shows must be the output we get: the acceptance summary line, the reproduction
  summary, and a stated runtime;
* the dependency table in `docs/deps.md` and `requirements.txt` must agree in **both** directions;
* no document is orphaned: every `docs/**/*.md` is reachable from the README or the plan.
"""
from __future__ import annotations

import hashlib
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from tools.puzzle import cli as C

README = ROOT / 'README.md'
DEPS = ROOT / 'docs' / 'deps.md'
REQ = ROOT / 'requirements.txt'
D = ROOT / 'recon' / 'derived'

checks: list[dict] = []


def check(name: str, passed: bool, detail: str = '') -> None:
    checks.append({'check': name, 'passed': bool(passed), 'detail': detail})


def discovered_gates() -> int:
    from tools.checks.run_all import gate_paths
    return len(list(gate_paths()))


def main() -> int:
    if not README.exists():
        print('missing README.md')
        return 1
    text = README.read_text(encoding='utf-8')

    # ---- every command in the README exists ------------------------------------------
    stages = {s for s, _m, _p, _x in C.STAGES}
    used = set(re.findall(r'-m\s+tools\.puzzle\s+([a-z0-9-]+)', text))
    unknown = sorted(used - stages)
    check('every pipeline command in the README is a real stage',
          not unknown, f'{len(used)} commands checked; unknown: {unknown or "none"}')

    gate_refs = set(re.findall(r'tools/checks/([a-z0-9_]+\.py)', text))
    missing = sorted(g for g in gate_refs if not (ROOT / 'tools' / 'checks' / g).exists())
    check('every gate the README names exists on disk',
          not missing, f'{len(gate_refs)} gates cited; missing: {missing or "none"}')

    # ---- its counts are current ------------------------------------------------------
    live = discovered_gates()
    stated = [int(n) for n in re.findall(r'all (\d+) gates', text)]
    check('the gate count in the README equals the count the suite discovers',
          stated and all(n == live for n in stated), f'README says {stated or "nothing"}, live is {live}')
    stages_stated = [int(n) for n in re.findall(r'the (\d+) pipeline stages', text)]
    pipeline_len = len([s for s in C.STAGES if s[0] != 'reproduce'])
    check('the stage count in the README equals the pipeline',
          stages_stated and all(n == pipeline_len for n in stages_stated),
          f'README says {stages_stated or "nothing"}, pipeline has {pipeline_len} '
          f'(the table has {len(C.STAGES)} entries, including `reproduce` itself)')

    # ---- the prerequisites are the real ones -----------------------------------------
    prereqs = {'the upstream puzzle repo': 'asic-puzzle-2026' in text,
               'the dependency manifest': 'requirements.txt' in text,
               'iverilog': 'iverilog' in text,
               'git': re.search(r'\bgit\b', text) is not None}
    check('the README states every real prerequisite',
          all(prereqs.values()),
          ', '.join(k for k, v in prereqs.items() if not v) or 'upstream repo, requirements, iverilog, git')

    # ---- the output it shows is the output we get ------------------------------------
    acc = json.loads((D / 'acceptance.json').read_text(encoding='utf-8'))
    cnt = acc['counts']
    summary_line = f"{cnt['PASS']} PASS, {cnt['PARTIAL']} PARTIAL, {cnt['FAIL']} FAIL"
    outputs = {'acceptance summary': summary_line in text,
               'reproduction summary': 'regenerated byte-identically' in text,
               'a stated runtime': re.search(r'\d+(\.\d+)?\s*(s|minutes)\b', text) is not None,
               'the honest PARTIAL': 'PARTIAL' in text and 'not claim' in text.lower()}
    check('the README shows the acceptance summary, the reproduction summary and a runtime',
          all(outputs.values()), ', '.join(k for k, v in outputs.items() if not v) or 'all present')

    # ---- deps.md and requirements.txt agree, both ways -------------------------------
    req_pkgs = {m.group(1) for m in re.finditer(r'^([A-Za-z0-9_.-]+)\s*==', REQ.read_text(encoding='utf-8'),
                                               re.M)}
    deps_text = DEPS.read_text(encoding='utf-8')
    section1 = deps_text.split('## 2.')[0]
    deps_pkgs = set(re.findall(r'^\|\s*`([a-z0-9_.-]+)`\s*\|', section1, re.M))
    check('requirements.txt and docs/deps.md list the same packages',
          req_pkgs == deps_pkgs,
          f'only in requirements: {sorted(req_pkgs - deps_pkgs) or "none"}; '
          f'only in deps.md: {sorted(deps_pkgs - req_pkgs) or "none"}')

    # ---- nothing is orphaned ---------------------------------------------------------
    # Matched on the document's stem, not its file name: the plan cites steps as `A1`, `C4`, and a
    # gate that demanded `A1.md` would be checking a spelling rather than a link.
    docs = {p.stem for p in (ROOT / 'docs').rglob('*.md')}
    plan = (ROOT / 'docs' / '03_our_plan.md').read_text(encoding='utf-8')
    orphans = [d for d in sorted(docs) if d not in text and d not in plan]
    check('every document is reachable from the README or the plan',
          not orphans, f'{len(docs)} documents; orphans: {orphans or "none"}')

    # ---- the layout section names what exists ----------------------------------------
    dirs = [d for d in ('build', 'recon/derived', 'tools/puzzle', 'tools/checks', 'docs')
            if f'{d}' in text and (ROOT / d).is_dir()]
    check('the README describes the repository layout that exists',
          len(dirs) == 5, f'{len(dirs)}/5 directories described and present')

    # ---- every provenance stamp is true ------------------------------------------------
    # F5 (2026-09-13), from the post-review audit: build/cells.v named recon/derived/pin_names.json
    # and recon/derived/netlist_check.json but printed puzzle.gds's hash for both -- the same hash
    # twice, and neither file's actual hash. A stamp that cannot detect a stale input is worse than
    # no stamp, because it looks like evidence. This check reads every hash a generated file claims,
    # pairs it with the path on the *same line*, and tests it against that file.
    #
    # Two shapes exist in build/: `sha256 <hex>` next to a path (cells.v), and puzzle.v's per-stage
    # lines carrying a bare hex token, which its own header declares to be the hash of the GDS.
    gds_sha = hashlib.sha256((ROOT / 'asic-puzzle-2026' / 'puzzle.gds').read_bytes()).hexdigest()
    path_re = re.compile(r'((?:recon|tools|build|docs|asic-puzzle-2026)/[A-Za-z0-9_./-]+?'
                         r'\.(?:json|csv|vcd|py|v))(?=\s|$)')
    build_files = sorted((ROOT / 'build').glob('*.v'))
    bad_stamps: list[str] = []
    claims = 0
    for v in build_files:
        lines = v.read_text(encoding='utf-8', errors='replace').splitlines()
        for lineno, line in enumerate(lines, 1):
            m = re.search(r'sha256 ([0-9a-f]{8,64})\s*$', line)
            bare = re.match(r'\s*//\s+(\S+)\s+(\S+)\s+([0-9a-f]{16})\s*$', line)
            if m:
                claims += 1
                # cells.v puts the path beside the hash; replay_tb.v puts it on the line above.
                # Either way, the path is never taken from a line that already carries another hash.
                found = path_re.search(line) or (
                    path_re.search(lines[lineno - 2]) if lineno >= 2 else None)
                if not found:
                    bad_stamps.append(f'{v.name}:{lineno}: sha256 with no path on or above its line')
                    continue
                rel, claimed = found.group(1), m.group(1)
                full = ROOT / rel
                if not full.exists():
                    bad_stamps.append(f'{v.name}:{lineno}: names {rel}, which does not exist')
                elif not hashlib.sha256(full.read_bytes()).hexdigest().startswith(claimed[:16]):
                    bad_stamps.append(
                        f'{v.name}:{lineno}: claims {claimed[:16]} for {rel}, actual '
                        f'{hashlib.sha256(full.read_bytes()).hexdigest()[:16]}')
            elif bare:
                claims += 1
                if not gds_sha.startswith(bare.group(3)):
                    bad_stamps.append(f'{v.name}:{lineno}: stage {bare.group(1)} prints '
                                      f'{bare.group(3)}, which is not the GDS hash')
    check('every provenance stamp in build/*.v names a file at the hash it prints',
          not bad_stamps,
          f'{claims} hashes in {len(build_files)} files; {bad_stamps or "every claim holds"}')

    # ---- the two artifacts that state the answer name their inputs --------------------
    # F5: `solutions.json` and `acceptance.json` are the artifacts a reader trusts most, so they must
    # carry the hashes of what they read. Twelve other artifacts do not, and for those the fault grid
    # is the control: each is registered, and its mutation must fire its owning gate (sweep evidence
    # in docs/verification.md). These two are the exception, not the rule.
    stale_src = []
    named = 0
    for name in ('solutions.json', 'acceptance.json'):
        d = json.loads((D / name).read_text(encoding='utf-8'))
        src = d.get('source') or {}
        if not src:
            stale_src.append(f'{name}: records no source hashes at all')
        for rel, want in src.items():
            named += 1
            p = ROOT / rel
            if not p.exists() or hashlib.sha256(p.read_bytes()).hexdigest() != want:
                stale_src.append(f'{name}: {rel} is stale or missing')
    check('the answer and the matrix name their inputs, at current hashes',
          not stale_src, f'{named} hashes verified; {stale_src or "all current"}')

    failed = [c for c in checks if not c['passed']]
    width = max(len(c['check']) for c in checks)
    for c in checks:
        print(f'  {"PASS" if c["passed"] else "FAIL"}  {c["check"]:<{width}}  {c["detail"]}')
    print()
    print(f'{len(checks) - len(failed)}/{len(checks)} checks passed')
    if failed:
        print('STEP F2 GATE: FAIL')
        return 1
    print('STEP F2 GATE: PASS')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
