#!/usr/bin/env python3
"""check_stepC5.py -- the C5 gate.

C5 asked a question that does not depend on knowing the map: does the design enforce anything beyond
22 ones, two per row, two per column and no 8-neighbour adjacency? Its answer was yes -- boards that
satisfy every visible rule are rejected anyway -- and that answer is what makes the hidden constraint
real rather than assumed.

What this gate holds in place:

* **The instrument**, re-validated against `example_inputs.vcd` on every run, because the message
  readings below are the evaluator's, not `iverilog`'s.
* **The claim, re-derived from scratch.** The boards are regenerated by this project's generator, the
  design is asked about each one through its own output stream, and every one must be rejected. The
  boards are also checked to satisfy the visible rules first: a board rejected *because* it breaks
  two-per-row would prove nothing.
* **The scope of the claim.** C5's finding is "a hidden constraint exists", not "here is the map".
  The gate asserts the measured discriminating power of that rejection test (from C4's controls) so
  the weaker reading cannot quietly become the stronger one: a board being rejected is very nearly
  uninformative about *which* partition is the real one.
"""
from __future__ import annotations

import json
import random
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from tools.puzzle import verdict as V

ART_C5 = ROOT / 'recon' / 'derived' / 'c5_rejections.json'
ART_C4 = ROOT / 'recon' / 'derived' / 'c4_partition.json'
MIN_BOARDS = 20
MAX_POWER = 0.15

checks: list[dict] = []


def check(name: str, passed: bool, detail: str = '') -> None:
    checks.append({'check': name, 'passed': bool(passed), 'detail': detail})


def main() -> int:
    for path in (ART_C5, ART_C4):
        if not path.exists():
            print(f'missing {path.relative_to(ROOT).as_posix()}')
            print('run: python -m tools.puzzle rejections   (and region-map, for the controls)')
            return 1
    art = json.loads(ART_C5.read_text(encoding='utf-8'))
    c4 = json.loads(ART_C4.read_text(encoding='utf-8'))

    m = V.Machine(cycles=V.MESSAGE_CYCLES)

    # ---- the instrument --------------------------------------------------------------
    rep = m.reference_replay()
    check('the evaluator reproduces example_inputs.vcd',
          rep['mismatches'] == 0 and rep['unknown_bits'] == 0,
          f"{rep['mismatches']} mismatches, {rep['unknown_bits']} unknown bits over "
          f"{rep['cycles']} cycles")

    # ---- the boards, regenerated -----------------------------------------------------
    board = V.derived_board()
    boards = [b for b in V.two_switch_boards(40)
              if b['all_ok'] and set(map(tuple, b['cells'])) != board]
    check(f'at least {MIN_BOARDS} boards satisfying every visible rule were generated',
          len(boards) >= MIN_BOARDS, f'{len(boards)} boards')
    check('every board satisfies 22 ones, two per row, two per column, no adjacency',
          all(V.visible_rules(b['cells'])['all_ok'] for b in boards),
          'so a rejection cannot be explained by a visible rule')
    check('no board is the derived board',
          all(set(map(tuple, b['cells'])) != board for b in boards),
          f'{len(boards)} distinct')

    # ---- the claim: the design rejects every one of them -----------------------------
    accepted, messages, unknown = 0, {}, 0
    for b in boards:
        r = m.message(V.pattern_from_cells(b['cells']))
        messages[b['seed']] = r['text']
        unknown += r['unknown_bits']
        accepted += 1 if (r['text'] == '(* TWO STARS *)' or r['success_cycle_0based'] is not None) \
            else 0
    check('the design accepts none of them, and says so on its own output stream',
          accepted == 0, f'{accepted} of {len(boards)} accepted')
    check('the derived board is the reference point: it is still accepted',
          m.message([int(b) for b in V.derived_feed()])['text'] == '(* TWO STARS *)',
          'the derived vector answers (* TWO STARS *)')
    check('the rejections are the generic message, not an adjacency complaint',
          all(v == 'TRY AGAIN' for v in messages.values()),
          f"{sorted(set(messages.values()))}")
    check('no unknown bits in the messages read off this window',
          unknown == 0, f'{unknown} unknown bits')

    # ---- the artifact must be these boards, not older ones ---------------------------
    art_seeds = {b['seed'] for b in art['boards']}
    art_msgs = {b['seed']: b.get('message') for b in art['boards']}
    check('the committed artifact holds the same boards the gate just generated',
          art_seeds == set(messages), f'{len(art_seeds)} artifact vs {len(messages)} live')
    check('the committed messages match the re-derived ones',
          art_msgs == messages, 'identical' if art_msgs == messages else 'drifted')
    check('the artifact s own totals agree with the board list it stores',
          art['accepted'] == 0 and art['rejected'] == len(art['boards'])
          and art['generated'] >= len(art['boards']),
          f"{len(art['boards'])} boards, {art['accepted']} accepted, {art['rejected']} rejected "
          f"of {art['generated']} generated")
    check('the artifact s recorded replay matches the live one',
          art['reference_replay']['mismatches'] == rep['mismatches']
          and art['reference_replay']['unknown_bits'] == rep['unknown_bits']
          and art['reference_replay']['cycles'] == rep['cycles'],
          f"artifact {art['reference_replay']['mismatches']}/"
          f"{art['reference_replay']['unknown_bits']} vs live {rep['mismatches']}/{rep['unknown_bits']}")

    # ---- the scope of the claim: control A, moved here from C4 (review R1/R5/R8) -----
    # This stage owns the rejected boards, so the control measured against them belongs with it: does
    # "no class over 2" separate C4's partition from a same-shape look-alike? If most look-alikes also
    # reject every one of these boards, the rejections carry almost no information about the map.
    ragged = [c for c in c4['candidates'] if not c['is_the_visible_column_rule']]
    rt = art.get('rejection_test') or {}
    power = rt.get('discriminating_power')
    check('control A: the rejection test has weak discriminating power (recorded)',
          rt.get('lookalikes_tested') == 200 and power is not None and power <= MAX_POWER,
          f"{rt.get('lookalikes_that_also_reject_every_board')} of {rt.get('lookalikes_tested')} "
          f"look-alikes also reject every board (power {power!r})")
    # ... and the recording is checked, not trusted: 200 look-alike partitions of the same shape,
    # each asked whether it also rejects all these boards. Cheap (170k cell tests), so re-derived live.
    board_cells = [set(map(tuple, b['cells'])) for b in boards]
    rng_a, trials_a, pass_a = random.Random(1), 200, 0
    for _ in range(trials_a):
        look = V.same_shape_partitions(rng_a, ragged[0]['class_sizes'], board)
        ok = True
        for b in board_cells:
            load = [0] * 11
            for cell in b:
                load[look[cell[0] * 11 + cell[1]]] += 1
            if max(load) <= 2:
                ok = False
                break
        pass_a += 1 if ok else 0
    check('control A re-derived live matches the artifact',
          pass_a == rt.get('lookalikes_that_also_reject_every_board'),
          f"live {pass_a} vs artifact {rt.get('lookalikes_that_also_reject_every_board')}")

    # ---- anti-vacuity floors ---------------------------------------------------------
    check('floors: boards, comparisons and message bytes',
          len(boards) >= MIN_BOARDS and rep['output_comparisons'] > 1000
          and sum(len(v) for v in messages.values()) >= 8 * len(boards),
          f'{len(boards)} boards, {rep["output_comparisons"]} comparisons, '
          f'{sum(len(v) for v in messages.values())} message chars')

    failed = [c for c in checks if not c['passed']]
    width = max(len(c['check']) for c in checks)
    for c in checks:
        print(f'  {"PASS" if c["passed"] else "FAIL"}  {c["check"]:<{width}}  {c["detail"]}')
    print()
    print(f'{len(checks) - len(failed)}/{len(checks)} checks passed')
    if failed:
        print('STEP C5 GATE: FAIL')
        return 1
    print('STEP C5 GATE: PASS')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
