#!/usr/bin/env python3
"""check_stepF2.py -- F2: is the documentation true, not just present?

F2's verify clause is "following the README from a clean clone reproduces E4's output". Nobody can
clone-and-run inside a gate, but almost everything that makes that claim *true* is checkable, and the
ways a README goes false are exactly the ways it drifts:

* every command it prints must exist -- each `python -m tools.puzzle <stage>` must be a stage in
  `cli.STAGES`, and each `tools/checks/<file>.py` must be a gate on disk;
* its counts must be current: the gate count it states must equal the number of gates the suite
  actually discovers, so adding a gate without touching the README fails here;
* the prerequisites it lists must be the real ones -- the upstream puzzle repo, `requirements.txt`,
  `iverilog`, `git` -- because those are what the pipeline refuses to run without;
* the output it shows must be the output we get: the acceptance summary line, the reproduction
  summary, and a stated runtime;
* the dependency table in `docs/deps.md` and `requirements.txt` must agree in **both** directions;
* no document is orphaned: every `docs/**/*.md` is reachable from the README or the plan.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from tools.puzzle import cli as C

README = ROOT / 'README.md'
DEPS = ROOT / 'docs' / 'deps.md'
REQ = ROOT / 'requirements.txt'

checks: list[dict] = []


def check(name: str, passed: bool, detail: str = '') -> None:
    checks.append({'check': name, 'passed': bool(passed), 'detail': detail})


def discovered_gates() -> int:
    from tools.checks.run_all import gate_paths
    return len(list(gate_paths()))


def main() -> int:
    if not README.exists():
        print('missing README.md')
        return 1
    text = README.read_text(encoding='utf-8')

    # ---- every command in the README exists ------------------------------------------
    stages = {s for s, _m, _p, _x in C.STAGES}
    used = set(re.findall(r'-m\s+tools\.puzzle\s+([a-z0-9-]+)', text))
    unknown = sorted(used - stages)
    check('every pipeline command in the README is a real stage',
          not unknown, f'{len(used)} commands checked; unknown: {unknown or "none"}')

    gate_refs = set(re.findall(r'tools/checks/([a-z0-9_]+\.py)', text))
    missing = sorted(g for g in gate_refs if not (ROOT / 'tools' / 'checks' / g).exists())
    check('every gate the README names exists on disk',
          not missing, f'{len(gate_refs)} gates cited; missing: {missing or "none"}')

    # ---- its counts are current ------------------------------------------------------
    live = discovered_gates()
    stated = [int(n) for n in re.findall(r'all (\d+) gates', text)]
    check('the gate count in the README equals the count the suite discovers',
          stated and all(n == live for n in stated), f'README says {stated or "nothing"}, live is {live}')
    stages_stated = [int(n) for n in re.findall(r'the (\d+) pipeline stages', text)]
    pipeline_len = len([s for s in C.STAGES if s[0] != 'reproduce'])
    check('the stage count in the README equals the pipeline',
          stages_stated and all(n == pipeline_len for n in stages_stated),
          f'README says {stages_stated or "nothing"}, pipeline has {pipeline_len} '
          f'(the table has {len(C.STAGES)} entries, including `reproduce` itself)')

    # ---- the prerequisites are the real ones -----------------------------------------
    prereqs = {'the upstream puzzle repo': 'asic-puzzle-2026' in text,
               'the dependency manifest': 'requirements.txt' in text,
               'iverilog': 'iverilog' in text,
               'git': re.search(r'\bgit\b', text) is not None}
    check('the README states every real prerequisite',
          all(prereqs.values()),
          ', '.join(k for k, v in prereqs.items() if not v) or 'upstream repo, requirements, iverilog, git')

    # ---- the output it shows is the output we get ------------------------------------
    outputs = {'acceptance summary': '5 PASS, 1 PARTIAL, 0 FAIL' in text,
               'reproduction summary': 'regenerated byte-identically' in text,
               'a stated runtime': re.search(r'\d+(\.\d+)?\s*(s|minutes)\b', text) is not None,
               'the honest PARTIAL': 'PARTIAL' in text and 'not claim' in text.lower()}
    check('the README shows the acceptance summary, the reproduction summary and a runtime',
          all(outputs.values()), ', '.join(k for k, v in outputs.items() if not v) or 'all present')

    # ---- deps.md and requirements.txt agree, both ways -------------------------------
    req_pkgs = {m.group(1) for m in re.finditer(r'^([A-Za-z0-9_.-]+)\s*==', REQ.read_text(encoding='utf-8'),
                                               re.M)}
    deps_text = DEPS.read_text(encoding='utf-8')
    section1 = deps_text.split('## 2.')[0]
    deps_pkgs = set(re.findall(r'^\|\s*`([a-z0-9_.-]+)`\s*\|', section1, re.M))
    check('requirements.txt and docs/deps.md list the same packages',
          req_pkgs == deps_pkgs,
          f'only in requirements: {sorted(req_pkgs - deps_pkgs) or "none"}; '
          f'only in deps.md: {sorted(deps_pkgs - req_pkgs) or "none"}')

    # ---- nothing is orphaned ---------------------------------------------------------
    # Matched on the document's stem, not its file name: the plan cites steps as `A1`, `C4`, and a
    # gate that demanded `A1.md` would be checking a spelling rather than a link.
    docs = {p.stem for p in (ROOT / 'docs').rglob('*.md')}
    plan = (ROOT / 'docs' / '03_our_plan.md').read_text(encoding='utf-8')
    orphans = [d for d in sorted(docs) if d not in text and d not in plan]
    check('every document is reachable from the README or the plan',
          not orphans, f'{len(docs)} documents; orphans: {orphans or "none"}')

    # ---- the layout section names what exists ----------------------------------------
    dirs = [d for d in ('build', 'recon/derived', 'tools/puzzle', 'tools/checks', 'docs')
            if f'{d}' in text and (ROOT / d).is_dir()]
    check('the README describes the repository layout that exists',
          len(dirs) == 5, f'{len(dirs)}/5 directories described and present')

    failed = [c for c in checks if not c['passed']]
    width = max(len(c['check']) for c in checks)
    for c in checks:
        print(f'  {"PASS" if c["passed"] else "FAIL"}  {c["check"]:<{width}}  {c["detail"]}')
    print()
    print(f'{len(checks) - len(failed)}/{len(checks)} checks passed')
    if failed:
        print('STEP F2 GATE: FAIL')
        return 1
    print('STEP F2 GATE: PASS')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
