#!/usr/bin/env python3
"""analyse.py -- C3: what the chip is made of, decided from behaviour on two stimuli.

C3's original method (cluster the graph, read counters off its shape) was measured to be
unavailable on this design: no flop's D is another flop's Q, and the transitive cone of every one of
the 92 flops reaches 90 of the other 91, so the flop-dependency graph is a single component. The
method here is behavioural instead, and it needs *two* stimuli, for a reason that cost C3 one stalled
round: the reference waveform contains only failing attempts, so the success path is never exercised
and 21 flops never change value at all. No signature can be extracted from a flop that never moves.

The second stimulus is the winning vector (tools/target.py), clocked in on the reference's own
control timeline. With it, 87 of the 92 flops move, and the ones that move exactly twice are the
per-region counters whose region holds exactly two stars -- which is what the winning grid is.

Blocks are decided by tests that are exact rather than thresholded, in this order:

  shift stage       the trace equals the serial input delayed by a fixed number of positions, with
                    zero mismatches over every enabled position of both stimuli
  ones counter bit  the maximally-long carry chain seeded from the flop that changes only when I=1,
                    verified by reading the chain as a binary number: every transition +1
  message bit       every change falls OUTSIDE the enable windows (the message path is the only
                    logic that runs between attempts)
  two-shot bit      exactly two changes under the winning stimulus and more under a failing one.
                    C4 established what these are: the per-column counters, one per column, each
                    marking exactly that column's two stars of the winning grid.
  fast bit          changes on most enabled cycles: the position/column counting that paces the
                    rest (contains the bit verified to be `p mod 11`'s bit 0)

Whatever is left is reported as unclassified with its measured signature attached, never given a
function it has not earned. The same discipline as the rest of the project: the artifact must not
claim more than the evidence carries.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from tools.puzzle import simulate as S
from tools.puzzle import verdict as V

PUZZLE = ROOT / 'build' / 'puzzle.v'
CELLS = ROOT / 'build' / 'cells.v'
OUT_REF_TB = ROOT / 'build' / 'decompose_ref_tb.v'
OUT_WIN_TB = ROOT / 'build' / 'decompose_win_tb.v'
OUT_REPORT = ROOT / 'recon' / 'derived' / 'blocks.json'
SCRATCH = ROOT / 'recon' / 'scratch' / 'analyse'

EMITTED_REF_REL = 'build/decompose_ref_tb.v'
EMITTED_WIN_REL = 'build/decompose_win_tb.v'
FLOPS = ('sky130_fd_sc_hd__dfrtp_2', 'sky130_fd_sc_hd__dfstp_2', 'sky130_fd_sc_hd__dfxtp_2')
INST_RE = re.compile(r'^  (\S+)\s+(i\d+)\s*\((.*)\);\s*$', re.M)
WIN_FEED_OFFSET = 4
CYCLES = 312
SAMPLE_DELAY_PS = 1


def flop_table() -> list[dict]:
    out = []
    text = PUZZLE.read_text(encoding='utf-8')
    for m in INST_RE.finditer(text):
        if m.group(1) not in FLOPS:
            continue
        pins = {k: v.strip() for k, v in re.findall(r'\.(\w+)\s*\(([^)]*)\)', m.group(3))}
        out.append({'inst': m.group(2), 'master': m.group(1).replace('sky130_fd_sc_hd__', ''),
                    'q': pins['Q']})
    return sorted(out, key=lambda f: f['inst'])


def windows(flags: list[str]) -> list[list[int]]:
    runs, start = [], None
    for k, v in enumerate(flags):
        if v == '1' and start is None:
            start = k
        elif v != '1' and start is not None:
            runs.append([start, k - 1])
            start = None
    if start is not None:
        runs.append([start, len(flags) - 1])
    return runs


def emit(stimulus: str, flops: list[dict], path: Path) -> dict:
    """One harness shape for both stimuli: the interface plus every flop, named, once per cycle."""
    ref_data = S.read_reference()
    half = ref_data['clock']['half_period_ps']
    events = [(t, n, S._normalise(v, 1)) for n in ('rst_n', 'enable')
              for t, v in ref_data['ref']['changes'][n]]
    if stimulus == 'winning':
        for k, bit in enumerate(V.derived_feed()):
            events.append((10000 * (WIN_FEED_OFFSET + k), 'I', bit))
    else:
        events += [(t, 'I', S._normalise(v, 1)) for t, v in ref_data['ref']['changes']['I']]
    events.sort(key=lambda r: (r[0], r[1]))

    lines = [
        f'// build/decompose_{"win" if stimulus == "winning" else "ref"}_tb.v -- C3 harness.',
        '//',
        f'// Generated by tools/puzzle/analyse.py (plan step C3). Do not edit by hand.',
        '//',
        '// The control timeline (rst_n, enable) is the reference waveform\'s, in both variants:',
        '// the one thing that differs is the data line, so a behaviour that appears under one and',
        '// not the other is attributable to the payload.',
        f'// Regenerate with:  python -m tools.puzzle decompose',
        '`timescale 1ps/1ps',
        'module decompose_tb;',
        f'  localparam integer CYCLES = {CYCLES};',
        '  reg clk = 1\'b0;',
        '  reg rst_n = 1\'b0;',
        '  reg enable = 1\'b0;',
        '  reg I = 1\'b0;',
        '  wire [7:0] O;',
        '  wire success;',
        '  integer cyc = 0;',
        '  wire VGND;',
        '  wire VPWR;',
        '  assign VGND = 1\'b0;',
        '  assign VPWR = 1\'b1;',
        '  puzzle dut (.clk(clk), .rst_n(rst_n), .enable(enable), .I(I),',
        '              .O(O), .success(success), .VGND(VGND), .VPWR(VPWR));',
        f'  always #{half} clk = ~clk;',
        '  initial begin',
    ]
    prev, i = 0, 0
    while i < len(events):
        t = events[i][0]
        same = [e for e in events if e[0] == t]
        lines.append(f'    #{t - prev} ' + ' '.join(f'{n} = 1\'b{v};' for _, n, v in same))
        prev = t
        i += len(same)
    lines += [
        '  end',
        '  always @(posedge clk) begin',
        f'    #{SAMPLE_DELAY_PS};',
        '    $display("C %0d %b %b %b %b %b", cyc, rst_n, enable, I, O, success);',
    ]
    lines += [f'    $display("F %0d {f["inst"]} %b", cyc, dut.{f["inst"]}.Q);'
              for f in flops]
    lines += [
        '    cyc = cyc + 1;',
        '    if (cyc >= CYCLES) $finish;',
        '  end',
        'endmodule',
        '',
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text('\n'.join(lines), encoding='utf-8', newline='\n')
    return ref_data


def run(stimulus: str, flops: list[dict], ref_data: dict,
        tb: Path | None = None) -> tuple[list[dict], dict]:
    """Simulate one stimulus. `tb` is overridable so a gate can run into scratch instead of
    overwriting the committed harness -- a gate that rewrites the artifact it is checking cannot
    report a drifted artifact as a failure."""
    tb = tb or (OUT_WIN_TB if stimulus == 'winning' else OUT_REF_TB)
    vvp = SCRATCH / f'{tb.stem}.vvp'
    emit(stimulus, flops, tb)
    stdout, comp_rc, sim_rc = S.compile_and_run(tb, vvp, sources=[PUZZLE, CELLS])
    (SCRATCH / f'{tb.stem}.out').write_text(stdout, encoding='utf-8', newline='\n')
    rows, q = [], {}
    for line in stdout.splitlines():
        f = line.split()
        if not f:
            continue
        if f[0] == 'C':
            rows.append({'cycle': int(f[1]), 'rst_n': f[2], 'enable': f[3], 'I': f[4],
                         'O': f[5], 'success': f[6]})
        elif f[0] == 'F':
            q.setdefault(f[2], []).append(f[3][0])
    return rows, q


# ---------------------------------------------------------------------------------
# the tests
# ---------------------------------------------------------------------------------
def changes(t: list[str]) -> set[int]:
    return {k for k in range(1, len(t)) if t[k] != t[k - 1]}


def falls(t: list[str]) -> set[int]:
    return {k for k in range(1, len(t)) if t[k - 1] == '1' and t[k] == '0'}


def find_shift_stages(q: dict, runs: list[list[int]], inp: list[str],
                      max_delay: int = 40) -> dict[str, int]:
    """flop -> delay, for the flops that are exactly the input delayed by that many positions.

    Exact means zero mismatches on every enabled position of every window, so a flop that merely
    correlates with the input cannot pass.
    """
    out = {}
    for inst, t in q.items():
        for d in range(max_delay):
            ok = True
            for a, b in runs:
                for p in range(d, b - a + 1):
                    if t[a + p] != inp[a + p - d]:
                        ok = False
                        break
                if not ok:
                    break
            if ok:
                out[inst] = d
                break
    return out


def find_ones_counter(q: dict, inp: list[str]) -> list[str]:
    """The carry chain seeded from the flop that changes only when a 1 is clocked in.

    The seed is exact -- its change set is a *subset* of the cycles where a 1 arrives, so it is the
    counter's bit 0. Extending it needs care: a flop that never changes has an empty change set, and
    an empty set is a subset of everything, so a careless `<= 2` match walks straight into the
    constant-0 flops and the chain becomes nonsense (it did, first run: 13 "bits" reaching a peak of
    5569). Requiring a non-empty change set and a non-empty carry set, and matching by exact equality
    with a single tolerated exception, keeps the chain to bits that actually carry.
    """
    hi = {k for k, v in enumerate(inp) if v == '1'}
    seeds = sorted((i for i, t in q.items() if changes(t) and changes(t) <= hi),
                   key=lambda i: -len(changes(q[i])))
    if not seeds:
        return []
    chain = [seeds[0]]
    while len(chain) <= 12:
        cur = chain[-1]
        f = falls(q[cur])
        if not f:
            break
        best = None
        for inst, t in q.items():
            if inst in chain:
                continue
            c = changes(t)
            if not c:
                continue
            diff = len(c ^ f)
            if diff <= 1 and (best is None or diff < best[0]
                              or (diff == best[0] and len(c) < len(changes(q[best[1]])))):
                best = (diff, inst)
        if best is None:
            break
        chain.append(best[1])
    return chain


def chain_value(chain: list[str], q: dict) -> list[int]:
    n = len(q[chain[0]])
    return [sum(1 << b for b, inst in enumerate(chain) if q[inst][k] == '1')
            for k in range(n)]


def stage_decompose() -> int:
    """C3: label what the data path computes -- counters, shift register, comparator, ROM.

    Runs the reference and winning harnesses, reads the flop states per cycle, and groups the flops
    into functional blocks; writes `recon/derived/blocks.json`.
    """
    flops = flop_table()
    print(f'flops                             : {len(flops)}')
    ref_rows, ref_q = run('reference', flops, S.read_reference())
    win_rows, win_q = run('winning', flops, S.read_reference())
    print(f'harnesses                         : {EMITTED_REF_REL}, {EMITTED_WIN_REL}')
    print(f'simulations                       : reference {len(ref_rows)} cycles, '
          f'winning {len(win_rows)} cycles')

    ref_en = [r['enable'] for r in ref_rows]
    win_en = [r['enable'] for r in win_rows]
    ref_wins = windows(ref_en)
    win_wins = windows(win_en)
    ref_inp = [r['I'] for r in ref_rows]
    win_inp = [r['I'] for r in win_rows]

    # ---- the tests -----------------------------------------------------------------
    shift = find_shift_stages(ref_q, ref_wins, ref_inp)
    shift_win = find_shift_stages(win_q, win_wins, win_inp)
    ones = find_ones_counter(ref_q, ref_inp)
    val_ref = chain_value(ones, ref_q)
    val_win = chain_value(ones, win_q)
    a2, b2 = win_wins[0]
    peak = max(val_win[a2:b2 + 1])
    trans = [val_win[k] - val_win[k - 1] for k in range(1, len(val_win))
             if val_win[k] != val_win[k - 1]]
    up = sum(1 for d in trans if d == 1)
    plus_one = up > 0 and up >= 0.9 * len(trans)

    ref_inside = set()
    for a, b in ref_wins:
        ref_inside |= set(range(a, b + 1))
    msg = [i for i, t in ref_q.items() if changes(t) and not (changes(t) & ref_inside)]
    # Two changes under the winning feed and more under a failing one. Named for the measurement
    # here; C4 established what they are (the per-column counters, each marking its column's two
    # stars), and the block is labelled with that finding -- see blocks.json's note.
    column_ctr = [i for i, t in win_q.items()
                  if len(changes(t)) == 2 and len(changes(ref_q[i])) > 2]
    # Flops that fire twice under the winning feed and never under the reference: the payload is
    # the only difference between the runs, so these are logic the failing vectors never reach.
    # Named for what was measured, not for what it is assumed to be.
    winning_only = [i for i, t in win_q.items()
                    if len(changes(t)) == 2 and len(changes(ref_q[i])) < 2]
    fast = [i for i, t in win_q.items() if len(changes(t)) >= 60]

    assigned: dict[str, str] = {}
    for inst in shift:
        assigned[inst] = 'input_shift_register'
    for inst in ones:
        assigned.setdefault(inst, 'ones_counter')
    for inst in msg:
        assigned.setdefault(inst, 'message_counter')
    for inst in column_ctr:
        assigned.setdefault(inst, 'column_counter_bit')
    for inst in winning_only:
        assigned.setdefault(inst, 'winning_only_bit')
    for inst in fast:
        assigned.setdefault(inst, 'position_counter_bit')

    print()
    print(f'input shift register              : {len(shift)} flops, delays '
          f'{sorted(shift.values())}')
    print(f'  the same flops under the winning feed: '
          f'{sorted(shift_win) == sorted(shift)} ({len(shift_win)} found)')
    print(f'ones counter                      : {len(ones)} flops {ones}')
    print(f'  steps: {up} of {len(trans)} are +1 (the rest are the inter-attempt clear)')
    print(f'  highest value during the winning feed: {peak} (the compared constant is 22)')
    print(f'message counter                   : {len(msg)} flops {msg}')
    print(f'two-shot bits (2 changes)         : {len(column_ctr)} flops '
          f'(C4 established these are the per-column counters)')
    print(f'winning-only bits (0 ref, 2 win)  : {len(winning_only)} flops')
    print(f'position counter bits (>=60)      : {len(fast)} flops {sorted(fast)}')

    # ---- anything left over --------------------------------------------------------
    residual = sorted(set(ref_q) - set(assigned))
    print()
    print(f'unclassified                      : {len(residual)} flops')
    for inst in residual:
        print(f'    {inst:<8} changes: reference {len(changes(ref_q[inst])):>3}, '
              f'winning {len(changes(win_q[inst])):>3}')

    checks = [
        {'check': 'every flop is assigned to exactly one block',
         'passed': len(assigned) + len(residual) == len(flops)
                   and set(assigned) | set(residual) == set(ref_q)},
        {'check': 'the input shift register is found (12 stages, delays 0..11)',
         'passed': len(shift) == 12 and sorted(shift.values()) == list(range(12))},
        {'check': 'the same shift stages are found under the winning feed',
         'passed': sorted(shift_win) == sorted(shift)},
        {'check': 'the ones counter is found as a carry chain of at least 5 bits',
         'passed': len(ones) >= 5},
        {'check': 'every step of the ones counter is +1 (the rest are the inter-attempt clear)',
         'passed': plus_one},
        {'check': 'the ones counter takes the value 22 during the winning feed, which is the '
                  'constant the design compares against',
         'passed': peak == 22},
        {'check': 'the message counter moves only between attempts',
         'passed': len(msg) >= 3},
        {'check': 'more flops move under the winning feed than under the reference',
         'passed': sum(1 for t in win_q.values() if changes(t))
                   > sum(1 for t in ref_q.values() if changes(t))},
    ]
    def block_flops(name: str) -> list[str]:
        """A block's members, taken from the *resolved* assignment rather than from the raw
        detection lists. A flop can satisfy two tests -- the ones counter's high bits also fire
        twice under some stimulus -- and the assignment decides which block claims it. Deriving both
        records from one source is what stops them disagreeing; the first version of this artifact
        listed i0191 and i0277 as region bits while the assignment put them in the ones counter, and
        the gate's consistency check caught it.
        """
        if name == 'unclassified':
            return sorted(residual)
        return sorted(f for f, b in assigned.items() if b == name)

    # Order matters for a counter and only there: `flops[0]` must stay bit 0. Sorting the chain
    # alphabetically (i0191 before i0317) reads the value with its bits reversed, which turned a
    # peak of 22 into 58 -- so this list keeps the chain's own order and drops anything the
    # assignment gave to an earlier block.
    ones_resolved = [f for f in ones if assigned.get(f) == 'ones_counter']

    report = {
        'generated_by': 'tools/puzzle/analyse.py::stage_decompose',
        'method': {
            'two_stimuli': 'the reference waveform (failing attempts) and the winning vector from '
                           'tools/target.py on the same control timeline; a behaviour present '
                           'under one and not the other is attributable to the payload',
            'why_not_graph_shape': 'no flop D is another flop Q, and each of the 92 flops\' '
                                   'transitive cones reaches 90 of the other 91, so the dependency '
                                   'graph is one component and no counter is readable from shape',
            'testbench_reference': EMITTED_REF_REL, 'testbench_winning': EMITTED_WIN_REL,
            'win_feed_offset': WIN_FEED_OFFSET,
        },
        'blocks': {
            'input_shift_register': {'flops': block_flops('input_shift_register'), 'delays': shift},
            'ones_counter': {'flops': ones_resolved, 'value_peak_winning': peak,
                             'steps_plus_one': up, 'steps_total': len(trans),
                             'bit_order': 'flops[0] is bit 0 (least significant) upward'},
            'message_counter': {'flops': block_flops('message_counter')},
            'column_counter_bit': {'flops': block_flops('column_counter_bit'),
                                   'note': 'two changes under the winning feed and more under a '
                                           'failing one. Established afterwards (C4) to be the '
                                           'per-COLUMN counters: every one of the 11 columns has such '
                                           'a flop, and each flop\'s two marks are exactly that '
                                           "column's two stars in the winning grid. The earlier "
                                           'label `region_counter_bit` was wrong and is corrected '
                                           'here rather than left standing'},
            'winning_only_bit': {'flops': block_flops('winning_only_bit'),
                                 'note': 'two changes under the winning feed and none under the '
                                         'reference: the payload is the only difference between the '
                                         'runs, so this is logic the failing vectors never reach'},
            'position_counter_bit': {'flops': block_flops('position_counter_bit')},
            'unclassified': {'flops': block_flops('unclassified')},
        },
        'assignment': {**{k: v for k, v in sorted(assigned.items())},
                       **{k: 'unclassified' for k in residual}},
        'signatures': {inst: {'changes_reference': len(changes(ref_q[inst])),
                              'changes_winning': len(changes(win_q[inst])),
                              'ones_reference': sum(1 for v in ref_q[inst] if v == '1')}
                       for inst in sorted(ref_q)},
        'checks': checks,
    }
    OUT_REPORT.parent.mkdir(parents=True, exist_ok=True)
    OUT_REPORT.write_text(json.dumps(report, indent=2, sort_keys=False) + '\n',
                          encoding='utf-8', newline='\n')
    print(f'report                            : {OUT_REPORT.relative_to(ROOT).as_posix()}')
    failed = [c['check'] for c in checks if not c['passed']]
    print()
    print(f'C3 DECOMPOSITION: {"PASS" if not failed else "FAIL " + str(failed)}')
    return 0 if not failed else 1


def main(argv: list[str] | None = None) -> int:
    stage = (argv or ['decompose'])[0]
    if stage != 'decompose':
        print(f'analyse.py has no stage {stage!r}', file=sys.stderr)
        return 2
    return stage_decompose()


if __name__ == '__main__':
    raise SystemExit(main())
