#!/usr/bin/env python3
"""emit.py -- B6: write the structure back out as Verilog.

``build/puzzle.v`` is a structural netlist of the whole chip: every one of B1's instances,
with every pin B4 resolved connected to the net B3 found, in our own net-naming scheme.
The cell models live in ``build/cells.v`` (tools/puzzle/cells.py); this file contains no
behaviour at all.

Net naming, in full -- it is deliberately mechanical so that the file can be read back and
checked against the artifacts it came from:

* a net that carries only supply pins is named by the supply it carries (``VPWR``/``VGND``),
  because those are the chip's own port labels for them;
* a net one of the 13 documented ports sits on is named by that port (``clk``, ``rst_n``,
  ``enable``, ``I``, ``O[0]``...``O[7]``, ``success``);
* every other net is ``n<cluster>``, where ``cluster`` is B3's own net identity.

No net is renamed, merged, or dropped, so the inverse of that map is exact and the B6 gate
uses it to rebuild B4's ``(instance, pin) -> net`` table from the emitted text alone.

Pins B4 could not assign are emitted as explicit empty connections (``.VPB()``) rather than
quietly omitted, so the file shows the same 972 unassigned pins the artifact records,
attributed to the same two reasons (A5's two gap classes). Nothing is hidden and nothing is
invented: a pin with no net in the layout gets no net in the Verilog.
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from tools.puzzle.connect import read_json                      # noqa: E402

B1 = ROOT / 'recon' / 'derived' / 'instances.json'
B3 = ROOT / 'recon' / 'derived' / 'nets.json'
B4 = ROOT / 'recon' / 'derived' / 'pin_net.json'
B5 = ROOT / 'recon' / 'derived' / 'netlist_check.json'
A3 = ROOT / 'recon' / 'derived' / 'pin_names.json'
OUT = ROOT / 'build' / 'puzzle.v'

TOP = 'puzzle'
#: The documented interface, in the order docs/01_problem.md states it. The *sets* are
#: checked against the artifacts; only the presentation order is pinned here.
IN_ORDER = ('clk', 'rst_n', 'enable', 'I')
SUPPLY_ORDER = ('VGND', 'VPWR')


def net_names(b4: dict, b5: dict) -> dict[int, str]:
    """cluster -> Verilog net name, built by the rule in the module docstring."""
    names: dict[int, str] = {}
    for net in b4['nets']:
        if not net.get('is_supply_only'):
            continue
        carried = set(net['pin_names'])
        for supply in SUPPLY_ORDER:
            if supply in carried:
                names[net['cluster']] = supply
    for port in b5['ports']:
        names[port['net']] = port['port']
    return names


def build_netlist() -> str:
    a3, b1, b3, b4, b5 = (read_json(p) for p in (A3, B1, B3, B4, B5))
    names = net_names(b4, b5)

    # ---- the interface, checked against the artifact rather than assumed -------------
    ports = {p['port']: p for p in b5['ports']}
    ins = sorted(p for p, r in ports.items() if r['dir'] == 'in')
    outs = sorted(p for p, r in ports.items() if r['dir'] == 'out')
    assert tuple(sorted(IN_ORDER)) == tuple(ins), (ins, IN_ORDER)
    assert outs == ['O[0]', 'O[1]', 'O[2]', 'O[3]',
                    'O[4]', 'O[5]', 'O[6]', 'O[7]', 'success'], outs

    # ---- used nets -------------------------------------------------------------------
    insts = b4['instances']
    used: set[int] = set()
    for info in insts.values():
        for value in info['pins'].values():
            if value is not None:
                used.add(value[0])
    port_nets = {r['net'] for r in b5['ports']}
    supply_nets = {c for c, n in names.items() if n in SUPPLY_ORDER}
    wires = sorted(used - port_nets - supply_nets)

    unconnected = sum(1 for info in insts.values()
                      for value in info['pins'].values() if value is None)
    total_pins = sum(len(info['pins']) for info in insts.values())

    out: list[str] = []
    line = '// ' + '=' * 77
    out.append(line)
    out.append(f'// build/puzzle.v -- {TOP}: the whole chip, as structure.')
    out.append('//')
    out.append('// Generated by tools/puzzle/emit.py (plan step B6). Do not edit by hand.')
    out.append('// Compile with:  iverilog -t null build/puzzle.v build/cells.v')
    out.append('//')
    out.append('// Provenance (sha256 of the GDS each stage read):')
    for label, doc in (('instances', b1), ('nets', b3),
                       ('pins', b4), ('interface', b5), ('pin names', a3)):
        out.append(f'//   {label:<10} {doc.get("generated_by", "?")}  '
                   f'{doc.get("source", {}).get("sha256", "?")[:16]}')
    out.append('//')
    out.append(f'// {len(insts)} instances, {total_pins} pins, {len(used)} nets carrying a pin,')
    out.append(f'// {len(wires)} of them plain signal nets. Net names are our own: n<cluster> for')
    out.append('// signal nets, the port label for a port net, the supply name for a supply net.')
    out.append('//')
    out.append(f'// {unconnected} of the {total_pins} pins are emitted as explicit empty')
    out.append('// connections. They are exactly the pins B4 could not assign, and only ever')
    out.append('// two things: VPB/VNB well ties, which have no routeable geometry in this')
    out.append('// layout (A5), and the supply pins of the antenna diodes (A5). No functional')
    out.append('// pin is among them.')
    out.append(line)
    out.append('')
    out.append(f'module {TOP} ({", ".join([*IN_ORDER, "O", "success", *SUPPLY_ORDER])});')
    for p in IN_ORDER:
        out.append(f'  input {p};')
    out.append('  output [7:0] O;')
    out.append('  output success;')
    for p in SUPPLY_ORDER:
        out.append(f'  inout {p};')
    out.append('')
    out.extend(render_body(a3, b1['instances'], insts, names, wires))
    out.append('')
    out.append('endmodule')
    return '\n'.join(out) + '\n'


def render_body(a3: dict, instances: list[dict], pin_map: dict, names: dict,
                wires: list[int]) -> list[str]:
    """Wire declarations plus instance lines. Shared by B6 (the chip) and B7 (the warm-up).

    Nothing here knows which design it is rendering: it is handed placements in B1's schema, a
    pin->net map in B4's, a cluster->name table, and A3's pin lists. That is what lets B7 claim
    the *same emitter* ran on a second design, rather than a lookalike that might agree by
    accident.
    """
    lines = [f'  wire {names.get(c, f"n{c}")};' for c in wires]
    for inst in instances:
        iid = inst['id']
        info = pin_map[iid]
        assert info['master'] == inst['master'], (iid, info['master'], inst['master'])
        order = list(a3['masters'][inst['master']]['pins'])
        given = info['pins']
        assert set(order) == set(given), (iid, set(order) ^ set(given))
        conns = []
        for pin in order:
            value = given[pin]
            conns.append(f'.{pin}({names.get(value[0], f"n{value[0]}")})' if value
                         else f'.{pin}()')
        x, y = inst['origin_dbu']
        row = inst.get('row_line')
        lines.append('')
        lines.append(f'  // {iid}  {inst["master"]}  {inst["kind"]}  '
                     f'@ ({x / 1000:.3f}, {y / 1000:.3f}) um'
                     + (f', row {row}' if row is not None else ''))
        lines.append(f'  {inst["master"]} {iid} ({", ".join(conns)});')
    return lines


def stage_emit() -> int:
    text = build_netlist()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding='utf-8', newline='\n')
    print(f'emit: {OUT.relative_to(ROOT)}  ({len(text)} bytes, '
          f'{text.count(chr(10))} lines)')
    return 0


def main(argv: list[str] | None = None) -> int:
    stage = (argv or ['emit'])[0]
    if stage != 'emit':
        print(f'unknown stage for emit.py: {stage!r}', file=sys.stderr)
        return 2
    return stage_emit()


if __name__ == '__main__':
    raise SystemExit(main())
