#!/usr/bin/env python3
"""equiv.py -- C2: the warm-up, exhaustively, against the source it was built from.

C1's oracle is the chip's own waveform: real, but *one* stimulus, and it turned out to be able to
see 37 of the 66 cell models it negated. The warm-up offers a second, different oracle -- a design
whose Verilog we hold (`warmup/00_source.v`) and whose layout we extracted (`build/warmup.v`) --
and the plan asks for a sweep of `(A, B)` against `A + B == 496`.

What this stage does with that freedom
--------------------------------------
* **It compares against the RTL, not against a formula.** Both designs are instantiated in one
  testbench and driven by one stimulus, so the primary comparison is *our netlist vs the reference
  source*. The formula is checked too, but as a third assertion: the reference must implement
  `a + b == target`, and so must ours. Restating `A + B == 496` in Python and comparing against it
  would have made the source irrelevant -- and would not have noticed if our reading of the
  protocol (bit order, enabling, when S is valid) was wrong in the same way twice.
* **Exhaustive, not sampled.** C1 measured that sampling costs real coverage, and here the whole
  space is cheap: 8 serial bits per operand means every pair fits in one simulation of
  milliseconds of simulated time. Nothing is left to a random seed.
* **Nothing about the protocol is typed in.** The shift width, the comparison target, the serial
  order and the top module are all *read out of* `00_source.v`; if the upstream file changes, this
  follows it or fails loudly rather than silently testing something else.
* **The coverage claim is computed, not implied.** C1 is blind to 29 of 66 models. The warm-up
  instantiates 18 cell types, which is a subset of the chip's 69 -- so this second oracle can only
  reach the ones in that intersection. The report records the overlap and, in particular, how many
  models *neither* behavioural oracle reaches, because a large sweep must not be read as coverage
  of the library.

The reference is renamed, not rewritten
---------------------------------------
The emitted netlist is called `adder_demo` because it *is* that design, so one of the two modules
has to move. Renaming the reference keeps the committed netlist simulated exactly as emitted, and
the transformation is asserted to be nothing but a rename: one line differs from upstream, and it
is the module declaration. The renamed copy lives in `recon/scratch/` and is never committed --
it is Jane Street's source, and this project does not redistribute third-party files it can
regenerate from the upstream clone.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from tools.puzzle.simulate import CELLS, compile_and_run, sha256      # noqa: E402

WU_SRC = ROOT / 'asic-puzzle-2026' / 'warmup' / '00_source.v'
WU_DUT = ROOT / 'build' / 'warmup.v'
C1_POWER = ROOT / 'recon' / 'derived' / 'c1_power.json'
OUT_TB = ROOT / 'build' / 'warmup_equiv_tb.v'
OUT_REPORT = ROOT / 'recon' / 'derived' / 'warmup_equiv.json'

#: The renamed reference, regenerated by the stage and by the gate. Third-party source: it stays
#: in scratch, like `recon/sources/`, and nothing rests on it existing.
REF_V = ROOT / 'recon' / 'scratch' / 'c2' / 'warmup_ref.v'
REF_SUFFIX = '_ref'

#: A *literal*: the gate redirects OUT_TB into scratch to regenerate it hermetically, and an
#: artifact that embeds its own output path then differs from the committed one by that path alone.
EMITTED_REL = 'build/warmup_equiv_tb.v'

#: The netlist under test. A literal for the same reason: the harness must not embed a path that
#: depends on where the repository happens to live.
DUT_REL = 'build/warmup.v'

MOD_RE = re.compile(r'(?ms)^module\s+(\w+)\s*\((.*?)^endmodule')
SHIFT_RE = re.compile(r'(\w+)\s*<=\s*\{\s*\w+\[(\d+):0\]\s*,\s*(\w+)\s*\}')
WIDTH_RE = re.compile(r'output\s+reg\s*\[(\d+):0\]')
TARGET_RE = re.compile(r"==\s*\d*'d(\d+)")
INST_TMPL = r'\b%s\b\s+\w+\s*\('
INSTANCE_RE = re.compile(r'^  (sky130_fd_sc_hd__\w+)\s+\w+\s*\(', re.M)


def read_warmup_source() -> dict:
    """The reference's own protocol parameters, read out of the source rather than assumed."""
    text = WU_SRC.read_text(encoding='utf-8')
    modules = {m.group(1): m.group(0) for m in MOD_RE.finditer(text)}
    if not modules:
        raise ValueError(f'no modules in {WU_SRC.name}')

    shifter = width = shift_expr = None
    for name, body in modules.items():
        s, w = SHIFT_RE.search(body), WIDTH_RE.search(body)
        if s and w:
            shifter, shift_expr, width = name, ' '.join(s.group(0).split()), int(w.group(1)) + 1
            break
    if shifter is None or width is None:
        raise ValueError('no shift register with a declared width in the warm-up source')
    if SHIFT_RE.search(modules[shifter]).group(2) != str(width - 2):
        raise ValueError('the shift register does not shift by exactly one bit per cycle')

    target = next((int(m.group(1)) for b in modules.values() if (m := TARGET_RE.search(b))), None)
    if target is None:
        raise ValueError('no comparison constant in the warm-up source')
    top = next((n for n, b in modules.items() if re.search(INST_TMPL % shifter, b)), None)
    if top is None:
        raise ValueError(f'no module instantiates {shifter}')
    head = re.search(rf'^module\s+{top}\s*\(([^)]*)\)', text, re.M)
    if not head:
        raise ValueError(f'no port list for {top}')
    return {'path': WU_SRC.relative_to(ROOT).as_posix(), 'sha256': sha256(WU_SRC),
            'modules': sorted(modules), 'top': top, 'width': width, 'target': target,
            'shifter': shifter, 'shift': shift_expr,
            'serial_order': 'MSB first: each cycle shifts the register up and feeds the new bit in '
                            'at bit 0, so the bit fed in first ends up at bit width-1',
            'ports': [p.strip() for p in head.group(1).split(',')], 'text': text}


def rename_top(text: str, top: str, suffix: str = REF_SUFFIX) -> str:
    """The reference with only its top module renamed, so both designs can be instantiated."""
    return re.sub(rf'^module\s+{top}\b', f'module {top}{suffix}', text, count=1, flags=re.M)


def render_tb(src: dict) -> str:
    """The harness: both designs, one stimulus, every pair."""
    w, target = src['width'], src['target']
    limit, pairs = 1 << w, (1 << w) ** 2
    expected_high = sum(1 for a in range(limit) for b in range(limit) if a + b == target)
    return '\n'.join([
        '// =============================================================================',
        f'// {EMITTED_REL} -- C2: our extracted warm-up netlist against the source it came from.',
        '//',
        '// Generated by tools/puzzle/simulate.py (plan step C2). Do not edit by hand.',
        '// Regenerate with:  python -m tools.puzzle warmup-equiv',
        '// Compile with:     iverilog -g2012 -o equiv.vvp build/warmup_equiv_tb.v',
        '//                   build/warmup.v build/cells.v <renamed reference>',
        '//',
        '// Both designs are instantiated here and driven by one stimulus, so the comparison is',
        '// against the real RTL rather than against a formula written down twice:',
        '//',
        f'//   dut_ours  {DUT_REL}   our netlist, rebuilt from warmup/04_final.gds',
        f'//   dut_ref   {src["path"]}   the reference, top module renamed',
        f'//                                        ({src["top"]} -> {src["top"]}{REF_SUFFIX})',
        '//',
        '// The parameters below are read out of the source, not chosen here:',
        f'//   shift width {w}   comparison target {target}   pairs {pairs}',
        f'//   serial order: {src["serial_order"]}',
        f'//   shift expression: {src["shift"]}',
        '//',
        f'// Every one of the {pairs} pairs is visited; the sweep is exhaustive. C1 measured that 37',
        '// of the 66 cell models it negated are visible to the chip\'s waveform. This oracle is a',
        '// different design, and the report records exactly which models it can reach -- the',
        f'// warm-up instantiates {len(warmup_masters())} cells, so its reach is bounded by the',
        '// library it uses, and no part of this file claims more coverage than that.',
        '//',
        '// This checks FUNCTION, not timing: cycle-accurate behaviour is C1\'s question.',
        '//',
        '// Output: one `M <kind> ...` line per mismatch, at most 10 of each kind, then',
        '//   R checked=<n> ref_high=<n> ours_high=<n> mism_ours_vs_ref=<n>',
        '//     mism_ref_vs_func=<n> mism_ours_vs_func=<n>',
        '// =============================================================================',
        '',
        '`timescale 1ns/1ps',
        '',
        'module warmup_equiv_tb;',
        f'  localparam integer WIDTH = {w};',
        f'  localparam integer LIMIT = {limit};',
        f'  localparam integer TARGET = {target};',
        '',
        "  reg clk = 1'b0;",
        "  reg rst_n = 1'b0;",
        "  reg en = 1'b0;",
        "  reg A = 1'b0;",
        "  reg B = 1'b0;",
        '  wire S_ours, S_ref;',
        '',
        '  // The netlist declares its supply ports inout, so they need a net that supports',
        '  // continuous assignment. The reference has no supply ports at all.',
        '  wire VGND;',
        '  wire VPWR;',
        "  assign VGND = 1'b0;",
        "  assign VPWR = 1'b1;",
        '',
        "  adder_demo dut_ours (.A(A), .B(B), .S(S_ours), .clk(clk), .en(en), .rst_n(rst_n),",
        '                       .VGND(VGND), .VPWR(VPWR));',
        f'  {src["top"]}{REF_SUFFIX} dut_ref (.A(A), .B(B), .S(S_ref), .clk(clk), .en(en), '
        '.rst_n(rst_n));',
        '',
        '  always #5 clk = ~clk;',
        '',
        '  integer va, vb, bit_i;',
        '  integer checked = 0, ref_high = 0, ours_high = 0;',
        '  integer mism_ref = 0, mism_fn = 0, mism_ours = 0;',
        '  reg expected;',
        '',
        '  initial begin',
        "    rst_n = 1'b0;",
        "    en = 1'b0;",
        '    repeat (2) @(negedge clk);',
        "    rst_n = 1'b1;",
        "    en = 1'b1;",
        '    for (va = 0; va < LIMIT; va = va + 1) begin',
        '      for (vb = 0; vb < LIMIT; vb = vb + 1) begin',
        f'        // Shift {w} bits of each operand in, MSB first, one bit per enabled rising edge.',
        '        // No reset between pairs: WIDTH shifts overwrite the register completely.',
        '        for (bit_i = WIDTH - 1; bit_i >= 0; bit_i = bit_i - 1) begin',
        '          @(negedge clk);',
        '          A = (va >> bit_i) & 1;',
        '          B = (vb >> bit_i) & 1;',
        '          @(posedge clk);',
        '          #1;',
        '        end',
        '        checked = checked + 1;',
        '        expected = ((va + vb) == TARGET);',
        "        if (S_ref === 1'b1) ref_high = ref_high + 1;",
        "        if (S_ours === 1'b1) ours_high = ours_high + 1;",
        '        if (S_ours !== S_ref) begin',
        '          mism_ref = mism_ref + 1;',
        '          if (mism_ref <= 10)',
        '            $display("M ours_vs_ref ours=%b ref=%b va=%0d vb=%0d", S_ours, S_ref, va, vb);',
        '        end',
        '        if (S_ref !== expected) begin',
        '          mism_fn = mism_fn + 1;',
        '          if (mism_fn <= 10)',
        '            $display("M ref_vs_func ref=%b want=%0d va=%0d vb=%0d", S_ref, expected, va, vb);',
        '        end',
        '        if (S_ours !== expected) begin',
        '          mism_ours = mism_ours + 1;',
        '          if (mism_ours <= 10)',
        '            $display("M ours_vs_func ours=%b want=%0d va=%0d vb=%0d", S_ours, expected, va, vb);',
        '        end',
        '      end',
        '    end',
        '    $display("R checked=%0d ref_high=%0d ours_high=%0d mism_ours_vs_ref=%0d '
        'mism_ref_vs_func=%0d mism_ours_vs_func=%0d", checked, ref_high, ours_high,',
        '             mism_ref, mism_fn, mism_ours);',
        '    $finish;',
        '  end',
        'endmodule',
    ]) + '\n'


def parse_output(stdout: str) -> dict:
    """The harness's own summary line, plus its mismatch examples."""
    summary, examples = None, []
    for line in stdout.splitlines():
        f = line.split()
        if not f:
            continue
        if f[0] == 'R':
            summary = {k: int(v) for k, v in (p.split('=') for p in f[1:])}
        elif f[0] == 'M':
            examples.append(line.strip())
    if summary is None:
        raise RuntimeError(f'the harness printed no summary line; stdout was:\n{stdout[:2000]}')
    return {'summary': summary, 'examples': examples}


def warmup_masters() -> list[str]:
    """The cell types our emitted warm-up netlist uses."""
    return sorted(set(INSTANCE_RE.findall(WU_DUT.read_text(encoding='utf-8'))))


def ensure_harness() -> dict:
    """Regenerate the harness and the renamed reference, and return the parsed source.

    Both C2 and its power measurement need the same two files, and both must be able to produce
    them from upstream alone -- a harness that only exists because some earlier stage happened to
    leave it behind is not reproducible.
    """
    src = read_warmup_source()
    REF_V.parent.mkdir(parents=True, exist_ok=True)
    REF_V.write_text(rename_top(src['text'], src['top']), encoding='utf-8', newline='\n')
    OUT_TB.parent.mkdir(parents=True, exist_ok=True)
    OUT_TB.write_text(render_tb(src), encoding='utf-8', newline='\n')
    return src


def cross_oracle_overlap() -> dict:
    """Which models this oracle can reach that C1 could not, and which neither can reach.

    Computed rather than asserted: C1's measurement is per-model, the warm-up's library is a
    subset of the chip's, and their intersection is the only honest statement of what the second
    oracle adds.
    """
    used = set(warmup_masters())
    if not C1_POWER.exists():
        return {'available': False,
                'note': 'run `python -m tools.puzzle model-power` first'}
    pw = json.loads(C1_POWER.read_text(encoding='utf-8'))
    status = {r['model']: r['caught'] for r in pw['per_model'] if r['caught'] is not None}
    caught = {m for m, c in status.items() if c}
    silent = {m for m, c in status.items() if not c}
    neither = sorted(silent - used)
    return {'available': True, 'warmup_masters': len(used), 'c1_mutated': len(status),
            'c1_caught': sorted(used & caught), 'c1_silent': sorted(used & silent),
            'neither_oracle': neither,
            'note': f"C1 is blind to {len(silent)} of the {len(status)} models it negated; this "
                    f"oracle instantiates {len(used & silent)} of them, so {len(neither)} models "
                    f"are reached by neither behavioural oracle and rest on the B6 truth tables "
                    f"plus the reading of family names that they encode."}


def stage_warmup_equiv() -> int:
    """C2: validate our cell models exhaustively on the warm-up adder.

    Every input vector, against the design whose real netlist Jane Street published; writes
    `recon/derived/warmup_equiv.json`. This is the check C1 cannot make: C1 catches a wrong model
    only when it changes an observed output, and C2 catches it for all inputs by construction.
    """
    src = ensure_harness()
    renamed = REF_V.read_text(encoding='utf-8')
    diff = [i for i, (a, b) in enumerate(zip(src['text'].splitlines(),
                                             renamed.splitlines())) if a != b]
    text = OUT_TB.read_text(encoding='utf-8')

    limit = 1 << src['width']
    pairs = limit ** 2
    expected_high = sum(1 for a in range(limit) for b in range(limit) if a + b == src['target'])
    print(f'reference                         : {src["path"]}')
    print(f'  modules                         : {src["modules"]}')
    print(f'  top                             : {src["top"]}, ports {src["ports"]}')
    print(f'  protocol                        : {src["width"]} serial bits, {src["serial_order"]}')
    print(f'  target                          : a + b == {src["target"]}')
    print(f'  renamed for the harness         : {src["top"]} -> {src["top"]}{REF_SUFFIX} '
          f'({len(diff)} line differs from upstream)')
    print(f'emitted                           : {EMITTED_REL} ({len(text)} bytes)')
    print(f'sweep                             : {pairs} pairs, {expected_high} of them equate')

    stdout, comp_rc, sim_rc = compile_and_run(
        OUT_TB, ROOT / 'recon' / 'scratch' / 'c2' / 'equiv.vvp', [WU_DUT, CELLS, REF_V])
    parsed = parse_output(stdout)
    got = parsed['summary']
    print(f'simulation                        : iverilog rc={comp_rc}, vvp rc={sim_rc}')
    print(f'  pairs checked                   : {got["checked"]}')
    print(f'  S high: reference / ours        : {got["ref_high"]} / {got["ours_high"]}')
    print(f'  mismatches ours-vs-reference    : {got["mism_ours_vs_ref"]}')
    print(f'  mismatches reference-vs-formula : {got["mism_ref_vs_func"]}')
    print(f'  mismatches ours-vs-formula      : {got["mism_ours_vs_func"]}')

    overlap = cross_oracle_overlap()
    if overlap['available']:
        print(f'cross-oracle overlap              : C1 blind to {len(overlap["c1_silent"]) + len(overlap["neither_oracle"])} '
              f'models; the warm-up instantiates {len(overlap["c1_silent"])} of them; '
              f'{len(overlap["neither_oracle"])} are reached by neither oracle')

    checks = [
        {'check': 'the source parses: a shifter, a comparator, and a top that instantiates them',
         'passed': src['width'] > 1 and src['target'] > 0 and src['top'] != src['shifter']},
        {'check': 'the reference differs from upstream on exactly one line, the module name',
         'passed': len(diff) == 1 and
                   renamed.splitlines()[diff[0]].startswith(f'module {src["top"]}{REF_SUFFIX}')},
        {'check': 'the sweep is exhaustive over the whole input space',
         'passed': got['checked'] == pairs},
        {'check': 'the reference implements a + b == target on every pair',
         'passed': got['mism_ref_vs_func'] == 0},
        {'check': 'and asserts on exactly the pairs that equate',
         'passed': got['ref_high'] == expected_high},
        {'check': 'our netlist agrees with the reference on every pair',
         'passed': got['mism_ours_vs_ref'] == 0},
        {'check': 'and implements the same function on every pair',
         'passed': got['mism_ours_vs_func'] == 0},
        {'check': 'our S is not stuck: it is high on the same number of pairs',
         'passed': got['ours_high'] == expected_high},
        {'check': 'the equating pairs are a real minority, so the sweep is not trivial',
         'passed': 0 < expected_high < pairs},
        {'check': 'the cross-oracle overlap was computed from C1 s per-model measurement',
         'passed': overlap['available'] and overlap['c1_mutated'] > 0},
    ]

    report = {
        'generated_by': 'tools/puzzle/equiv.py::stage_warmup_equiv',
        'reference': {k: src[k] for k in ('path', 'sha256', 'modules', 'top', 'ports', 'width',
                                          'target', 'shift', 'serial_order')},
        'sut': {'path': DUT_REL, 'sha256': sha256(WU_DUT),
                'module': 'adder_demo', 'masters': len(warmup_masters()),
                'emitted_by': 'tools/puzzle/warmup.py (B7)'},
        'method': {
            'harness': 'both designs instantiated in one testbench and driven by one stimulus, so '
                       'the primary comparison is against the reference RTL and not against a '
                       'formula restated in Python',
            'protocol': f'{src["width"]} serial bits per operand, MSB first, one bit per enabled '
                        f'rising edge; S is combinational, sampled one time step after the last '
                        f'capture',
            'renamed_reference': f'{src["top"]} -> {src["top"]}{REF_SUFFIX} in a scratch copy, '
                                 f'regenerated from upstream, never committed; upstream differs '
                                 f'on {len(diff)} line',
            'exhaustive': True, 'checks_function_not_timing': True,
            'testbench': EMITTED_REL},
        'sweep': {'pairs': pairs, 'checked': got['checked'], 'equating_pairs': expected_high,
                  'reference_high': got['ref_high'], 'ours_high': got['ours_high']},
        'comparison': {'ours_vs_reference_mismatches': got['mism_ours_vs_ref'],
                       'reference_vs_function_mismatches': got['mism_ref_vs_func'],
                       'ours_vs_function_mismatches': got['mism_ours_vs_func'],
                       'examples': parsed['examples'],
                       'equivalent': got['mism_ours_vs_ref'] == 0},
        'cross_oracle': overlap,
        'compiler': {'iverilog_rc': comp_rc, 'vvp_rc': sim_rc},
        'checks': checks,
    }
    OUT_REPORT.parent.mkdir(parents=True, exist_ok=True)
    OUT_REPORT.write_text(json.dumps(report, indent=2, sort_keys=False) + '\n',
                          encoding='utf-8', newline='\n')
    print(f'report                            : {OUT_REPORT.relative_to(ROOT).as_posix()}')
    for e in parsed['examples'][:10]:
        print(f'  {e}')
    failed = [c['check'] for c in checks if not c['passed']]
    print()
    print(f'C2 WARM-UP EQUIVALENCE: {"PASS" if not failed else "FAIL " + str(failed)}')
    return 0 if not failed else 1


def main(argv: list[str] | None = None) -> int:
    stage = (argv or ['warmup-equiv'])[0]
    if stage != 'warmup-equiv':
        print(f'equiv.py has no stage {stage!r}', file=sys.stderr)
        return 2
    return stage_warmup_equiv()


if __name__ == '__main__':
    raise SystemExit(main())
